[package]
name = "in_memory_db"
version = "0.1.0"
authors = ["ArtieFuzzz"]
edition = "2021"

[lib]
name = "in_memory_db"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
